enableGlobalCache: true

# Per compatibilit\'e0 con strumenti legacy\
nmMode: hardlinks-local

# Per installazioni pi\'f9 veloci e pulite\
compressionLevel: 1

# Salta installazioni post-install non sicure\
unsafeHttpWhitelist:
  - registry.npmjs.org
